version: "2"
services:

  # Jaeger
  # If we were cool, we would use the agent, etc directly and configure
  # persistent storage. But this bundle is really designed for local dev.
  jaeger-all-in-one:
    image: "jaegertracing/all-in-one:1.49"
    ports:
      - "${JAEGER_UI_PORT}:16686"
      - "14250"
    restart: always

  # Collector
  otel-collector:
    image: "otel/opentelemetry-collector-contrib:0.84.0"
    volumes:
      - otel-jaeger-config:/etc/otel
    ports:
      - "${OTEL_COLLECTOR_PORT}:4317"
    depends_on:
      - jaeger-all-in-one
    restart: always

volumes:
  otel-jaeger-config:
    external: true
